env:
  es6: true
parserOptions:
  ecmaVersion: 2020
  sourceType: module
settings:
  react:
    version: detect
extends:
  - 'plugin:react/recommended'
  - '@alex-taxiera/eslint-config-esm'
rules:
  react/prop-types:
    - warn
